// 50 Job-Focused DSA Interview Reference Solutions
// Auto-generated from verified reference solutions suite

export interface ProblemSolutionRecord {
  levelNumber: number;
  title: string;
  optimalCode: string;
  timeComplexity: string;
  spaceComplexity: string;
  explanation: string;
  keyTakeaway: string;
}

export const ALL_50_SOLUTIONS: Record<number, ProblemSolutionRecord> = {
  1: {
    levelNumber: 1,
    title: "Valid Palindrome",
    optimalCode: "s = input()\ncleaned = [c.lower() for c in s if c.isalnum()]\nprint(cleaned == cleaned[::-1])",
    timeComplexity: "O(1)",
    spaceComplexity: "O(n)",
    explanation: "Filtering takes O(n) time and two-pointer verification compares characters in O(n) time and O(1) auxiliary space.",
    keyTakeaway: "Core interview pattern for Valid Palindrome: optimal O(1) time and O(n) auxiliary space.",
  },
  2: {
    levelNumber: 2,
    title: "Reverse Words in a Sentence",
    optimalCode: "s = input()\nwords = s.split()\nprint(\" \".join(words[::-1]))",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    explanation: "Splitting by whitespace runs in O(n) time, reversing takes O(n), and joining produces the normalized string in O(n).",
    keyTakeaway: "Core interview pattern for Reverse Words in a Sentence: optimal O(n) time and O(n) auxiliary space.",
  },
  3: {
    levelNumber: 3,
    title: "First Non-Repeating Character",
    optimalCode: "s = input()\ncounts = {}\nfor c in s:\n    counts[c] = counts.get(c, 0) + 1\nres = \"-1\"\nfor c in s:\n    if counts[c] == 1:\n        res = c\n        break\nprint(res)",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    explanation: "Two-pass frequency counting runs in O(n) time and requires O(k) space where k is the size of the alphabet.",
    keyTakeaway: "Core interview pattern for First Non-Repeating Character: optimal O(n) time and O(n) auxiliary space.",
  },
  4: {
    levelNumber: 4,
    title: "Valid Anagram",
    optimalCode: "s = input()\nt = input()\nif len(s) != len(t):\n    print(False)\nelse:\n    counts = {}\n    for c in s:\n        counts[c] = counts.get(c, 0) + 1\n    for c in t:\n        if c not in counts or counts[c] == 0:\n            print(False)\n            break\n        counts[c] -= 1\n    else:\n        print(True)",
    timeComplexity: "O(n log n)",
    spaceComplexity: "O(n)",
    explanation: "Sorting both strings takes O(n log n). Using a frequency hash table takes O(n) time and O(1) auxiliary space (26 lowercase English letters).",
    keyTakeaway: "Core interview pattern for Valid Anagram: optimal O(n log n) time and O(n) auxiliary space.",
  },
  5: {
    levelNumber: 5,
    title: "Run-Length String Compression",
    optimalCode: "s = input()\nif not s:\n    print(\"\")\nelse:\n    res = []\n    curr = s[0]\n    count = 1\n    for i in range(1, len(s)):\n        if s[i] == curr:\n            count += 1\n        else:\n            res.append(f\"{curr}{count}\")\n            curr = s[i]\n            count = 1\n    res.append(f\"{curr}{count}\")\n    print(\"\".join(res))",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    explanation: "Single-pass linear scan runs in O(n) time and uses O(n) space to build the compressed string representation.",
    keyTakeaway: "Core interview pattern for Run-Length String Compression: optimal O(n) time and O(n) auxiliary space.",
  },
  6: {
    levelNumber: 6,
    title: "Move Zeroes to End",
    optimalCode: "nums = list(map(int, input().split()))\ninsert_pos = 0\nfor x in nums:\n    if x != 0:\n        nums[insert_pos] = x\n        insert_pos += 1\nwhile insert_pos < len(nums):\n    nums[insert_pos] = 0\n    insert_pos += 1\nprint(\" \".join(map(str, nums)))",
    timeComplexity: "O(1)",
    spaceComplexity: "O(n)",
    explanation: "Two-pointer in-place partition runs in O(n) time with O(1) auxiliary space.",
    keyTakeaway: "Core interview pattern for Move Zeroes to End: optimal O(1) time and O(n) auxiliary space.",
  },
  7: {
    levelNumber: 7,
    title: "Two Sum (Target Pair Indices)",
    optimalCode: "nums = list(map(int, input().split()))\ntarget = int(input())\nseen = {}\nfor i, num in enumerate(nums):\n    diff = target - num\n    if diff in seen:\n        print(f\"{seen[diff]} {i}\")\n        break\n    seen[num] = i",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    explanation: "Hash map complement lookup accomplishes pair matching in O(n) time and O(n) space.",
    keyTakeaway: "Core interview pattern for Two Sum (Target Pair Indices): optimal O(n) time and O(n) auxiliary space.",
  },
  8: {
    levelNumber: 8,
    title: "Majority Element (Boyer-Moore)",
    optimalCode: "nums = list(map(int, input().split()))\ncandidate = None\ncount = 0\nfor x in nums:\n    if count == 0:\n        candidate = x\n    count += (1 if x == candidate else -1)\nprint(candidate)",
    timeComplexity: "O(1)",
    spaceComplexity: "O(n)",
    explanation: "Boyer-Moore Voting Algorithm finds the dominant element in O(n) time and O(1) auxiliary space.",
    keyTakeaway: "Core interview pattern for Majority Element (Boyer-Moore): optimal O(1) time and O(n) auxiliary space.",
  },
  9: {
    levelNumber: 9,
    title: "Missing Number in Sequence",
    optimalCode: "nums = list(map(int, input().split()))\nn = len(nums)\nexpected = n * (n + 1) // 2\nactual = sum(nums)\nprint(expected - actual)",
    timeComplexity: "O(1)",
    spaceComplexity: "O(n)",
    explanation: "Gauss summation formula solves this in O(n) time and O(1) space with no extra memory allocation.",
    keyTakeaway: "Core interview pattern for Missing Number in Sequence: optimal O(1) time and O(n) auxiliary space.",
  },
  10: {
    levelNumber: 10,
    title: "Rotate Array by K Steps",
    optimalCode: "nums = list(map(int, input().split()))\nk = int(input())\nif nums:\n    k = k % len(nums)\n    if k > 0:\n        nums = nums[-k:] + nums[:-k]\nprint(\" \".join(map(str, nums)))",
    timeComplexity: "O(1)",
    spaceComplexity: "O(n)",
    explanation: "Modular arithmetic k = k % n avoids redundant rotations. In-place triple-reversal runs in O(n) time and O(1) space.",
    keyTakeaway: "Core interview pattern for Rotate Array by K Steps: optimal O(1) time and O(n) auxiliary space.",
  },
  11: {
    levelNumber: 11,
    title: "Word Frequency Counter",
    optimalCode: "s = input()\nwords = s.lower().split()\ncounts = {}\nfor w in words:\n    counts[w] = counts.get(w, 0) + 1\nfor w in sorted(counts.keys()):\n    print(f\"{w}: {counts[w]}\")",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    explanation: "Hash mapping aggregates counts in O(n) time, and sorting distinct word keys takes O(u log u) where u <= n.",
    keyTakeaway: "Core interview pattern for Word Frequency Counter: optimal O(n) time and O(1) auxiliary space.",
  },
  12: {
    levelNumber: 12,
    title: "Intersection of Two Arrays",
    optimalCode: "nums1 = list(map(int, input().split()))\nnums2 = list(map(int, input().split()))\ninter = set(nums1).intersection(set(nums2))\nif inter:\n    print(\" \".join(map(str, sorted(inter))))\nelse:\n    print(\"\")",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    explanation: "Hash set conversion and intersection runs in O(n + m) time, followed by sorting the k intersection items in O(k log k).",
    keyTakeaway: "Core interview pattern for Intersection of Two Arrays: optimal O(n) time and O(1) auxiliary space.",
  },
  13: {
    levelNumber: 13,
    title: "Contains Duplicate II",
    optimalCode: "nums = list(map(int, input().split()))\nk = int(input())\npos = {}\nfound = False\nfor i, x in enumerate(nums):\n    if x in pos and i - pos[x] <= k:\n        found = True\n        break\n    pos[x] = i\nprint(found)",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    explanation: "Hash table tracking of last seen indices solves this in a single O(n) pass and O(min(n, k)) space.",
    keyTakeaway: "Core interview pattern for Contains Duplicate II: optimal O(n) time and O(n) auxiliary space.",
  },
  14: {
    levelNumber: 14,
    title: "Isomorphic Strings",
    optimalCode: "s = input()\nt = input()\nif len(s) != len(t):\n    print(False)\nelse:\n    print(len(set(s)) == len(set(t)) == len(set(zip(s, t))))",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    explanation: "Zip set comparison checks bijectivity in O(n) time and O(n) space.",
    keyTakeaway: "Core interview pattern for Isomorphic Strings: optimal O(n) time and O(n) auxiliary space.",
  },
  15: {
    levelNumber: 15,
    title: "Subarray with Zero Sum",
    optimalCode: "nums = list(map(int, input().split()))\nseen = set([0])\ncurr = 0\nfound = False\nfor x in nums:\n    curr += x\n    if curr in seen:\n        found = True\n        break\n    seen.add(curr)\nprint(found)",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    explanation: "Prefix sum tracking with a hash set achieves O(n) time and O(n) space.",
    keyTakeaway: "Core interview pattern for Subarray with Zero Sum: optimal O(n) time and O(n) auxiliary space.",
  },
  16: {
    levelNumber: 16,
    title: "Binary Search (Sorted Array)",
    optimalCode: "nums = list(map(int, input().split()))\ntarget = int(input())\nlow, high = 0, len(nums) - 1\nans = -1\nwhile low <= high:\n    mid = (low + high) // 2\n    if nums[mid] == target:\n        ans = mid\n        break\n    elif nums[mid] < target:\n        low = mid + 1\n    else:\n        high = mid - 1\nprint(ans)",
    timeComplexity: "O(log n)",
    spaceComplexity: "O(1)",
    explanation: "Binary search divides the search space by half at each step, yielding optimal O(log n) time complexity.",
    keyTakeaway: "Core interview pattern for Binary Search (Sorted Array): optimal O(log n) time and O(1) auxiliary space.",
  },
  17: {
    levelNumber: 17,
    title: "Remove Duplicates from Sorted Array",
    optimalCode: "nums = list(map(int, input().split()))\nif not nums:\n    print(\"\")\nelse:\n    write_idx = 1\n    for i in range(1, len(nums)):\n        if nums[i] != nums[i - 1]:\n            nums[write_idx] = nums[i]\n            write_idx += 1\n    print(\" \".join(map(str, nums[:write_idx])))",
    timeComplexity: "O(1)",
    spaceComplexity: "O(n)",
    explanation: "Two-pointer compaction executes in O(n) time and O(1) auxiliary space.",
    keyTakeaway: "Core interview pattern for Remove Duplicates from Sorted Array: optimal O(1) time and O(n) auxiliary space.",
  },
  18: {
    levelNumber: 18,
    title: "Squares of a Sorted Array",
    optimalCode: "nums = list(map(int, input().split()))\nn = len(nums)\nleft, right = 0, n - 1\nres = [0] * n\nidx = n - 1\nwhile left <= right:\n    l_sq = nums[left] ** 2\n    r_sq = nums[right] ** 2\n    if l_sq > r_sq:\n        res[idx] = l_sq\n        left += 1\n    else:\n        res[idx] = r_sq\n        right -= 1\n    idx -= 1\nprint(\" \".join(map(str, res)))",
    timeComplexity: "O(n log n)",
    spaceComplexity: "O(1)",
    explanation: "Two-pointer comparison from both boundaries yields an O(n) linear time solution without an O(n log n) sort.",
    keyTakeaway: "Core interview pattern for Squares of a Sorted Array: optimal O(n log n) time and O(1) auxiliary space.",
  },
  19: {
    levelNumber: 19,
    title: "Search Insert Position",
    optimalCode: "nums = list(map(int, input().split()))\ntarget = int(input())\nlow, high = 0, len(nums) - 1\nwhile low <= high:\n    mid = (low + high) // 2\n    if nums[mid] == target:\n        low = mid\n        break\n    elif nums[mid] < target:\n        low = mid + 1\n    else:\n        high = mid - 1\nprint(low)",
    timeComplexity: "O(log n)",
    spaceComplexity: "O(1)",
    explanation: "Binary search lower-bound termination naturally converges `low` to the insertion rank in O(log n) time.",
    keyTakeaway: "Core interview pattern for Search Insert Position: optimal O(log n) time and O(1) auxiliary space.",
  },
  20: {
    levelNumber: 20,
    title: "Valid Mountain Array",
    optimalCode: "nums = list(map(int, input().split()))\nn = len(nums)\ni = 0\nwhile i + 1 < n and nums[i] < nums[i + 1]:\n    i += 1\nif i == 0 or i == n - 1:\n    print(False)\nelse:\n    while i + 1 < n and nums[i] > nums[i + 1]:\n        i += 1\n    print(i == n - 1)",
    timeComplexity: "O(1)",
    spaceComplexity: "O(n)",
    explanation: "Single-pass climber simulation checks monotonicity in O(n) time and O(1) space.",
    keyTakeaway: "Core interview pattern for Valid Mountain Array: optimal O(1) time and O(n) auxiliary space.",
  },
  21: {
    levelNumber: 21,
    title: "Single Number (Bitwise XOR)",
    optimalCode: "nums = list(map(int, input().split()))\nres = 0\nfor x in nums:\n    res ^= x\nprint(res)",
    timeComplexity: "O(1)",
    spaceComplexity: "O(n)",
    explanation: "Bitwise XOR accumulator computes the single number in O(n) time and strictly O(1) extra space.",
    keyTakeaway: "Core interview pattern for Single Number (Bitwise XOR): optimal O(1) time and O(n) auxiliary space.",
  },
  22: {
    levelNumber: 22,
    title: "Number of 1 Bits (Hamming Weight)",
    optimalCode: "n = int(input())\ncount = 0\nwhile n > 0:\n    n &= (n - 1)\n    count += 1\nprint(count)",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    explanation: "Brian Kernighan's trick runs in O(set_bits) time, which is at most 32 or 64 steps for standard words.",
    keyTakeaway: "Core interview pattern for Number of 1 Bits (Hamming Weight): optimal O(n) time and O(1) auxiliary space.",
  },
  23: {
    levelNumber: 23,
    title: "Power of Two",
    optimalCode: "n = int(input())\nprint(n > 0 and (n & (n - 1)) == 0)",
    timeComplexity: "O(1)",
    spaceComplexity: "O(1)",
    explanation: "Bitwise test (n > 0 and (n & (n - 1)) == 0) computes the result in strictly O(1) time and space.",
    keyTakeaway: "Core interview pattern for Power of Two: optimal O(1) time and O(1) auxiliary space.",
  },
  24: {
    levelNumber: 24,
    title: "FizzBuzz Enterprise",
    optimalCode: "n = int(input())\nfor i in range(1, n + 1):\n    if i % 15 == 0:\n        print(\"FizzBuzz\")\n    elif i % 3 == 0:\n        print(\"Fizz\")\n    elif i % 5 == 0:\n        print(\"Buzz\")\n    else:\n        print(i)",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    explanation: "Linear iteration from 1 to n checking modulo operations runs in O(n) time.",
    keyTakeaway: "Core interview pattern for FizzBuzz Enterprise: optimal O(n) time and O(1) auxiliary space.",
  },
  25: {
    levelNumber: 25,
    title: "Greatest Common Divisor & LCM",
    optimalCode: "a = int(input())\nb = int(input())\ndef gcd(x, y):\n    while y:\n        x, y = y, x % y\n    return x\ng = gcd(a, b)\nl = (a * b) // g\nprint(f\"GCD: {g}, LCM: {l}\")",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    explanation: "Euclidean division operates in O(log(min(a, b))) time, making it exceptionally fast.",
    keyTakeaway: "Core interview pattern for Greatest Common Divisor & LCM: optimal O(n) time and O(1) auxiliary space.",
  },
  26: {
    levelNumber: 26,
    title: "Fibonacci Number (Nth Term)",
    optimalCode: "n = int(input())\nif n <= 1:\n    print(n)\nelse:\n    a, b = 0, 1\n    for _ in range(2, n + 1):\n        a, b = b, a + b\n    print(b)",
    timeComplexity: "O(1)",
    spaceComplexity: "O(n)",
    explanation: "Iterative state transition or memoization achieves O(n) time and O(1) space.",
    keyTakeaway: "Core interview pattern for Fibonacci Number (Nth Term): optimal O(1) time and O(n) auxiliary space.",
  },
  27: {
    levelNumber: 27,
    title: "Trailing Zeroes in Factorial",
    optimalCode: "n = int(input())\ncount = 0\nwhile n >= 5:\n    count += n // 5\n    n //= 5\nprint(count)",
    timeComplexity: "O(1)",
    spaceComplexity: "O(1)",
    explanation: "Legendre's sum counts multiples of powers of 5 in O(log_5 n) time and O(1) space.",
    keyTakeaway: "Core interview pattern for Trailing Zeroes in Factorial: optimal O(1) time and O(1) auxiliary space.",
  },
  28: {
    levelNumber: 28,
    title: "Fast Exponentiation (Pow)",
    optimalCode: "x = int(input())\nn = int(input())\ndef power(base, exp):\n    res = 1\n    while exp > 0:\n        if exp % 2 == 1:\n            res *= base\n        base *= base\n        exp //= 2\n    return res\nprint(power(x, n))",
    timeComplexity: "O(log n)",
    spaceComplexity: "O(1)",
    explanation: "Halving the exponent at each step takes O(log n) operations rather than linear multiplications.",
    keyTakeaway: "Core interview pattern for Fast Exponentiation (Pow): optimal O(log n) time and O(1) auxiliary space.",
  },
  29: {
    levelNumber: 29,
    title: "Digital Root (Add Digits)",
    optimalCode: "n = int(input())\nwhile n >= 10:\n    n = sum(int(c) for c in str(n))\nprint(n)",
    timeComplexity: "O(log n)",
    spaceComplexity: "O(1)",
    explanation: "Digit summation converges in O(log n) iterations, or O(1) using modulo 9 arithmetic.",
    keyTakeaway: "Core interview pattern for Digital Root (Add Digits): optimal O(log n) time and O(1) auxiliary space.",
  },
  30: {
    levelNumber: 30,
    title: "Monotonic Array Verification",
    optimalCode: "nums = list(map(int, input().split()))\nis_inc = True\nis_dec = True\nfor i in range(1, len(nums)):\n    if nums[i] > nums[i - 1]:\n        is_dec = False\n    if nums[i] < nums[i - 1]:\n        is_inc = False\nprint(is_inc or is_dec)",
    timeComplexity: "O(1)",
    spaceComplexity: "O(n)",
    explanation: "Linear scan with two boolean direction flags evaluates monotonicity in O(n) time and O(1) space.",
    keyTakeaway: "Core interview pattern for Monotonic Array Verification: optimal O(1) time and O(n) auxiliary space.",
  },
  31: {
    levelNumber: 31,
    title: "Valid Parentheses",
    optimalCode: "s = input()\nstack = []\npairs = {')': '(', '}': '{', ']': '['}\nvalid = True\nfor c in s:\n    if c in pairs:\n        if not stack or stack[-1] != pairs[c]:\n            valid = False\n            break\n        stack.pop()\n    else:\n        stack.append(c)\nif stack:\n    valid = False\nprint(valid)",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    explanation: "LIFO stack matching achieves optimal O(n) time and O(n) space.",
    keyTakeaway: "Core interview pattern for Valid Parentheses: optimal O(n) time and O(n) auxiliary space.",
  },
  32: {
    levelNumber: 32,
    title: "Implement Queue using Two Stacks",
    optimalCode: "import sys\nlines = sys.stdin.read().splitlines()\nif lines:\n    n = int(lines[0])\n    s_in = []\n    s_out = []\n    def move():\n        if not s_out:\n            while s_in:\n                s_out.append(s_in.pop())\n    for line in lines[1:n+1]:\n        parts = line.split()\n        cmd = parts[0]\n        if cmd == \"push\":\n            s_in.append(int(parts[1]))\n        elif cmd == \"pop\":\n            move()\n            if s_out:\n                print(s_out.pop())\n        elif cmd == \"peek\":\n            move()\n            if s_out:\n                print(s_out[-1])",
    timeComplexity: "O(1)",
    spaceComplexity: "O(1)",
    explanation: "Amortized O(1) time per operation since each element is moved between stacks at most once.",
    keyTakeaway: "Core interview pattern for Implement Queue using Two Stacks: optimal O(1) time and O(1) auxiliary space.",
  },
  33: {
    levelNumber: 33,
    title: "Next Greater Element I",
    optimalCode: "nums1 = list(map(int, input().split()))\nnums2 = list(map(int, input().split()))\nnext_greater = {}\nstack = []\nfor x in nums2:\n    while stack and stack[-1] < x:\n        next_greater[stack.pop()] = x\n    stack.append(x)\nres = [next_greater.get(x, -1) for x in nums1]\nprint(\" \".join(map(str, res)))",
    timeComplexity: "O(1)",
    spaceComplexity: "O(1)",
    explanation: "Monotonic stack maps all next greater elements in O(n) time, followed by O(1) query lookups.",
    keyTakeaway: "Core interview pattern for Next Greater Element I: optimal O(1) time and O(1) auxiliary space.",
  },
  34: {
    levelNumber: 34,
    title: "Backspace String Compare",
    optimalCode: "s = input()\nt = input()\ndef process(text):\n    st = []\n    for c in text:\n        if c == '#':\n            if st:\n                st.pop()\n        else:\n            st.append(c)\n    return st\nprint(process(s) == process(t))",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    explanation: "Stack simulation processes each character once in O(n + m) time and O(n + m) space.",
    keyTakeaway: "Core interview pattern for Backspace String Compare: optimal O(n) time and O(1) auxiliary space.",
  },
  35: {
    levelNumber: 35,
    title: "Simplify Unix File Path",
    optimalCode: "path = input()\nparts = path.split('/')\nstack = []\nfor p in parts:\n    if p == '' or p == '.':\n        continue\n    elif p == '..':\n        if stack:\n            stack.pop()\n    else:\n        stack.append(p)\nprint('/' + '/'.join(stack))",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    explanation: "Path token splitting and directory stack traversal runs in O(n) time and O(n) space.",
    keyTakeaway: "Core interview pattern for Simplify Unix File Path: optimal O(n) time and O(n) auxiliary space.",
  },
  36: {
    levelNumber: 36,
    title: "Matrix Transposition",
    optimalCode: "import sys\nlines = sys.stdin.read().splitlines()\nif lines:\n    R, C = map(int, lines[0].split())\n    matrix = [list(map(int, line.split())) for line in lines[1:R+1]]\n    for c in range(C):\n        col = [str(matrix[r][c]) for r in range(R)]\n        print(\" \".join(col))",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    explanation: "Matrix transposition accesses each entry once in O(R * C) time and constructs the inverted grid in O(R * C) space.",
    keyTakeaway: "Core interview pattern for Matrix Transposition: optimal O(n) time and O(1) auxiliary space.",
  },
  37: {
    levelNumber: 37,
    title: "Matrix Diagonal Sum",
    optimalCode: "import sys\nlines = sys.stdin.read().splitlines()\nif lines:\n    n = int(lines[0])\n    matrix = [list(map(int, line.split())) for line in lines[1:n+1]]\n    total = 0\n    for i in range(n):\n        total += matrix[i][i]\n        sec = n - 1 - i\n        if sec != i:\n            total += matrix[i][sec]\n    print(total)",
    timeComplexity: "O(1)",
    spaceComplexity: "O(1)",
    explanation: "Single-loop iteration across the N rows computes the diagonal sum in O(N) time and O(1) space.",
    keyTakeaway: "Core interview pattern for Matrix Diagonal Sum: optimal O(1) time and O(1) auxiliary space.",
  },
  38: {
    levelNumber: 38,
    title: "Search in a 2D Matrix",
    optimalCode: "import sys\nlines = sys.stdin.read().splitlines()\nif lines:\n    R, C = map(int, lines[0].split())\n    matrix = [list(map(int, line.split())) for line in lines[1:R+1]]\n    target = int(lines[R+1])\n    low, high = 0, R * C - 1\n    found = False\n    while low <= high:\n        mid = (low + high) // 2\n        r, c = mid // C, mid % C\n        val = matrix[r][c]\n        if val == target:\n            found = True\n            break\n        elif val < target:\n            low = mid + 1\n        else:\n            high = mid - 1\n    print(found)",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    explanation: "Virtual 1D coordinate mapping enables direct binary search in O(log(R * C)) time.",
    keyTakeaway: "Core interview pattern for Search in a 2D Matrix: optimal O(n) time and O(1) auxiliary space.",
  },
  39: {
    levelNumber: 39,
    title: "Flood Fill (2D Component)",
    optimalCode: "import sys\nlines = sys.stdin.read().splitlines()\nif lines:\n    R, C = map(int, lines[0].split())\n    image = [list(map(int, line.split())) for line in lines[1:R+1]]\n    sr, sc = map(int, lines[R+1].split())\n    new_color = int(lines[R+2])\n    orig = image[sr][sc]\n    if orig != new_color:\n        q = [(sr, sc)]\n        image[sr][sc] = new_color\n        while q:\n            r, c = q.pop()\n            for dr, dc in [(-1, 0), (1, 0), (0, -1), (0, 1)]:\n                nr, nc = r + dr, c + dc\n                if 0 <= nr < R and 0 <= nc < C and image[nr][nc] == orig:\n                    image[nr][nc] = new_color\n                    q.append((nr, nc))\n    for row in image:\n        print(\" \".join(map(str, row)))",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    explanation: "DFS/BFS visits each connected grid cell once in O(R * C) time and O(R * C) call stack space.",
    keyTakeaway: "Core interview pattern for Flood Fill (2D Component): optimal O(n) time and O(1) auxiliary space.",
  },
  40: {
    levelNumber: 40,
    title: "Rotate Matrix 90 Degrees Clockwise",
    optimalCode: "import sys\nlines = sys.stdin.read().splitlines()\nif lines:\n    n = int(lines[0])\n    matrix = [list(map(int, line.split())) for line in lines[1:n+1]]\n    for i in range(n):\n        for j in range(i + 1, n):\n            matrix[i][j], matrix[j][i] = matrix[j][i], matrix[i][j]\n    for row in matrix:\n        row.reverse()\n        print(\" \".join(map(str, row)))",
    timeComplexity: "O(1)",
    spaceComplexity: "O(1)",
    explanation: "Transposing followed by row reversal rotates the matrix in O(N^2) time and O(1) extra space.",
    keyTakeaway: "Core interview pattern for Rotate Matrix 90 Degrees Clockwise: optimal O(1) time and O(1) auxiliary space.",
  },
  41: {
    levelNumber: 41,
    title: "Longest Substring Without Repeating Characters",
    optimalCode: "s = input()\nlast = {}\nleft = 0\nmax_len = 0\nfor right, c in enumerate(s):\n    if c in last and last[c] >= left:\n        left = last[c] + 1\n    last[c] = right\n    max_len = max(max_len, right - left + 1)\nprint(max_len)",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    explanation: "Sliding window with character index hash map executes in linear O(n) time and O(min(m, n)) space.",
    keyTakeaway: "Core interview pattern for Longest Substring Without Repeating Characters: optimal O(n) time and O(n) auxiliary space.",
  },
  42: {
    levelNumber: 42,
    title: "Group Anagrams",
    optimalCode: "words = input().split()\ngroups = {}\nfor w in words:\n    key = \"\".join(sorted(w))\n    groups.setdefault(key, []).append(w)\nres = []\nfor g in groups.values():\n    res.append(sorted(g))\nres.sort(key=lambda g: g[0])\nfor g in res:\n    print(\" \".join(g))",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    explanation: "Sorting character signatures or character count tuples groups anagrams in O(n * k log k) time.",
    keyTakeaway: "Core interview pattern for Group Anagrams: optimal O(n) time and O(1) auxiliary space.",
  },
  43: {
    levelNumber: 43,
    title: "Container With Most Water",
    optimalCode: "heights = list(map(int, input().split()))\nleft, right = 0, len(heights) - 1\nmax_area = 0\nwhile left < right:\n    h = min(heights[left], heights[right])\n    max_area = max(max_area, h * (right - left))\n    if heights[left] < heights[right]:\n        left += 1\n    else:\n        right -= 1\nprint(max_area)",
    timeComplexity: "O(1)",
    spaceComplexity: "O(n)",
    explanation: "Greedy two-pointer shrinking examines every potentially optimal candidate in strictly O(n) time and O(1) space.",
    keyTakeaway: "Core interview pattern for Container With Most Water: optimal O(1) time and O(n) auxiliary space.",
  },
  44: {
    levelNumber: 44,
    title: "Subarray Sum Equals K",
    optimalCode: "nums = list(map(int, input().split()))\nk = int(input())\ncounts = {0: 1}\ncurr = 0\nans = 0\nfor x in nums:\n    curr += x\n    ans += counts.get(curr - k, 0)\n    counts[curr] = counts.get(curr, 0) + 1\nprint(ans)",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    explanation: "Prefix sum frequency counting enables exact target offset lookups in O(n) time and O(n) space.",
    keyTakeaway: "Core interview pattern for Subarray Sum Equals K: optimal O(n) time and O(n) auxiliary space.",
  },
  45: {
    levelNumber: 45,
    title: "Merge Overlapping Intervals",
    optimalCode: "import sys\nlines = sys.stdin.read().splitlines()\nif lines:\n    n = int(lines[0])\n    intervals = [list(map(int, line.split())) for line in lines[1:n+1]]\n    intervals.sort(key=lambda x: x[0])\n    merged = []\n    for inter in intervals:\n        if not merged or merged[-1][1] < inter[0]:\n            merged.append(inter)\n        else:\n            merged[-1][1] = max(merged[-1][1], inter[1])\n    for inter in merged:\n        print(f\"{inter[0]} {inter[1]}\")",
    timeComplexity: "O(n log n)",
    spaceComplexity: "O(1)",
    explanation: "Interval sorting takes O(n log n) time, followed by a linear O(n) sweep to merge overlapping spans.",
    keyTakeaway: "Core interview pattern for Merge Overlapping Intervals: optimal O(n log n) time and O(1) auxiliary space.",
  },
  46: {
    levelNumber: 46,
    title: "3Sum (Three Elements Zero Sum)",
    optimalCode: "nums = list(map(int, input().split()))\nnums.sort()\nn = len(nums)\ntriplets = []\nfor i in range(n - 2):\n    if i > 0 and nums[i] == nums[i - 1]:\n        continue\n    left, right = i + 1, n - 1\n    target = -nums[i]\n    while left < right:\n        s = nums[left] + nums[right]\n        if s == target:\n            triplets.append([nums[i], nums[left], nums[right]])\n            while left < right and nums[left] == nums[left + 1]:\n                left += 1\n            while left < right and nums[right] == nums[right - 1]:\n                right -= 1\n            left += 1\n            right -= 1\n        elif s < target:\n            left += 1\n        else:\n            right -= 1\nif not triplets:\n    print(\"None\")\nelse:\n    for t in triplets:\n        print(\" \".join(map(str, t)))",
    timeComplexity: "O(n^2)",
    spaceComplexity: "O(1)",
    explanation: "Sorting followed by two-pointer search achieves O(n^2) time and avoids O(n^3) brute force.",
    keyTakeaway: "Core interview pattern for 3Sum (Three Elements Zero Sum): optimal O(n^2) time and O(1) auxiliary space.",
  },
  47: {
    levelNumber: 47,
    title: "Longest Consecutive Sequence",
    optimalCode: "nums = list(map(int, input().split()))\nif not nums:\n    print(0)\nelse:\n    s = set(nums)\n    best = 0\n    for x in s:\n        if x - 1 not in s:\n            curr = x\n            streak = 1\n            while curr + 1 in s:\n                curr += 1\n                streak += 1\n            best = max(best, streak)\n    print(best)",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    explanation: "Hash set sequence expansion visits each number at most twice, guaranteeing strictly O(n) time complexity.",
    keyTakeaway: "Core interview pattern for Longest Consecutive Sequence: optimal O(n) time and O(1) auxiliary space.",
  },
  48: {
    levelNumber: 48,
    title: "Daily Temperatures (Monotonic Stack)",
    optimalCode: "temps = list(map(int, input().split()))\nn = len(temps)\nans = [0] * n\nstack = []\nfor i, t in enumerate(temps):\n    while stack and temps[stack[-1]] < t:\n        prev = stack.pop()\n        ans[prev] = i - prev\n    stack.append(i)\nprint(\" \".join(map(str, ans)))",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    explanation: "Monotonic decreasing stack processes each index with at most one push and one pop, yielding O(n) time and O(n) space.",
    keyTakeaway: "Core interview pattern for Daily Temperatures (Monotonic Stack): optimal O(n) time and O(n) auxiliary space.",
  },
  49: {
    levelNumber: 49,
    title: "Trapping Rain Water",
    optimalCode: "height = list(map(int, input().split()))\nif not height:\n    print(0)\nelse:\n    left, right = 0, len(height) - 1\n    left_max, right_max = 0, 0\n    water = 0\n    while left < right:\n        if height[left] < height[right]:\n            if height[left] >= left_max:\n                left_max = height[left]\n            else:\n                water += left_max - height[left]\n            left += 1\n        else:\n            if height[right] >= right_max:\n                right_max = height[right]\n            else:\n                water += right_max - height[right]\n            right -= 1\n    print(water)",
    timeComplexity: "O(1)",
    spaceComplexity: "O(n)",
    explanation: "Two-pointer elevation sweep guarantees optimal O(n) time and O(1) auxiliary space.",
    keyTakeaway: "Core interview pattern for Trapping Rain Water: optimal O(1) time and O(n) auxiliary space.",
  },
  50: {
    levelNumber: 50,
    title: "Sliding Window Maximum",
    optimalCode: "from collections import deque\nnums = list(map(int, input().split()))\nk = int(input())\nif not nums or k == 0:\n    print(\"\")\nelse:\n    q = deque()\n    res = []\n    for i, x in enumerate(nums):\n        while q and q[0] <= i - k:\n            q.popleft()\n        while q and nums[q[-1]] <= x:\n            q.pop()\n        q.append(i)\n        if i >= k - 1:\n            res.append(nums[q[0]])\n    print(\" \".join(map(str, res)))",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    explanation: "Monotonic double-ended queue ensures every array index is pushed and popped at most once, yielding optimal O(n) time and O(k) space.",
    keyTakeaway: "Core interview pattern for Sliding Window Maximum: optimal O(n) time and O(n) auxiliary space.",
  },
  51: {
    levelNumber: 51,
    title: "Two Sum (LeetCode #1)",
    optimalCode: "nums = list(map(int, input().split()))\ntarget = int(input())\n\nseen = {}\nfor i, x in enumerate(nums):\n    diff = target - x\n    if diff in seen:\n        print(f\"{seen[diff]} {i}\")\n        break\n    seen[x] = i\n",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    explanation: "Using a hash map allows looking up whether the complement exists in O(1) average time, achieving optimal O(n) overall time and O(n) space.",
    keyTakeaway: "Core interview pattern for Two Sum (LeetCode #1): optimal O(n) time and O(n) auxiliary space.",
  },
  52: {
    levelNumber: 52,
    title: "Container With Most Water (LeetCode #11)",
    optimalCode: "heights = list(map(int, input().split()))\n\nl, r = 0, len(heights) - 1\nmax_area = 0\n\nwhile l < r:\n    w = r - l\n    h = min(heights[l], heights[r])\n    area = w * h\n    if area > max_area:\n        max_area = area\n    if heights[l] < heights[r]:\n        l += 1\n    else:\n        r -= 1\n\nprint(max_area)\n",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    explanation: "Greedy two-pointer approach starts with maximum width and moves the limiting height inward in each step, guaranteeing O(n) time and O(1) space.",
    keyTakeaway: "Core interview pattern for Container With Most Water (LeetCode #11): optimal O(n) time and O(1) auxiliary space.",
  },
  53: {
    levelNumber: 53,
    title: "3Sum (LeetCode #15)",
    optimalCode: "nums = list(map(int, input().split()))\nnums.sort()\ntriplets = []\nn = len(nums)\n\nfor i in range(n - 2):\n    if nums[i] > 0:\n        break\n    if i > 0 and nums[i] == nums[i - 1]:\n        continue\n    l, r = i + 1, n - 1\n    while l < r:\n        s = nums[i] + nums[l] + nums[r]\n        if s < 0:\n            l += 1\n        elif s > 0:\n            r -= 1\n        else:\n            triplets.append(f\"{nums[i]} {nums[l]} {nums[r]}\")\n            l += 1\n            r -= 1\n            while l < r and nums[l] == nums[l - 1]:\n                l += 1\n            while l < r and nums[r] == nums[r + 1]:\n                r -= 1\n\nif triplets:\n    for t in triplets:\n        print(t)\nelse:\n    print(\"NONE\")\n",
    timeComplexity: "O(n^2)",
    spaceComplexity: "O(1)",
    explanation: "Sorting in O(n log n) and running two pointers for each fixed element runs in O(n^2) time with O(1) extra space beyond sorting.",
    keyTakeaway: "Core interview pattern for 3Sum (LeetCode #15): optimal O(n^2) time and O(1) auxiliary space.",
  },
  54: {
    levelNumber: 54,
    title: "3Sum Closest (LeetCode #16)",
    optimalCode: "nums = list(map(int, input().split()))\ntarget = int(input())\n\nnums.sort()\nn = len(nums)\nclosest = nums[0] + nums[1] + nums[2]\n\nfor i in range(n - 2):\n    l, r = i + 1, n - 1\n    while l < r:\n        curr = nums[i] + nums[l] + nums[r]\n        if abs(curr - target) < abs(closest - target):\n            closest = curr\n        if curr < target:\n            l += 1\n        elif curr > target:\n            r -= 1\n        else:\n            closest = target\n            break\n    if closest == target:\n        break\n\nprint(closest)\n",
    timeComplexity: "O(n^2)",
    spaceComplexity: "O(1)",
    explanation: "Sorted array two-pointer scan achieves O(n^2) time complexity and O(1) auxiliary space.",
    keyTakeaway: "Core interview pattern for 3Sum Closest (LeetCode #16): optimal O(n^2) time and O(1) auxiliary space.",
  },
  55: {
    levelNumber: 55,
    title: "4Sum (LeetCode #18)",
    optimalCode: "nums = list(map(int, input().split()))\ntarget = int(input())\n\nnums.sort()\nn = len(nums)\nquads = []\n\nfor i in range(n - 3):\n    if i > 0 and nums[i] == nums[i - 1]:\n        continue\n    for j in range(i + 1, n - 2):\n        if j > i + 1 and nums[j] == nums[j - 1]:\n            continue\n        l, r = j + 1, n - 1\n        while l < r:\n            s = nums[i] + nums[j] + nums[l] + nums[r]\n            if s < target:\n                l += 1\n            elif s > target:\n                r -= 1\n            else:\n                quads.append(f\"{nums[i]} {nums[j]} {nums[l]} {nums[r]}\")\n                l += 1\n                r -= 1\n                while l < r and nums[l] == nums[l - 1]:\n                    l += 1\n                while l < r and nums[r] == nums[r + 1]:\n                    r -= 1\n\nif quads:\n    for q in quads:\n        print(q)\nelse:\n    print(\"NONE\")\n",
    timeComplexity: "O(n^3)",
    spaceComplexity: "O(1)",
    explanation: "Generalization of 2-pointer scan runs in O(n^3) time and O(1) space, dramatically faster than O(n^4) brute force.",
    keyTakeaway: "Core interview pattern for 4Sum (LeetCode #18): optimal O(n^3) time and O(1) auxiliary space.",
  },
  56: {
    levelNumber: 56,
    title: "Longest Substring Without Repeating Characters (LeetCode #3)",
    optimalCode: "import sys\nlines = sys.stdin.read().splitlines()\ns = lines[0] if lines else \"\"\n\nseen = {}\nstart = 0\nmax_len = 0\n\nfor end, char in enumerate(s):\n    if char in seen and seen[char] >= start:\n        start = seen[char] + 1\n    seen[char] = end\n    max_len = max(max_len, end - start + 1)\n\nprint(max_len)\n",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    explanation: "Sliding window with hash map tracks seen indices in a single pass in O(n) time and O(min(n, alphabet)) auxiliary space.",
    keyTakeaway: "Core interview pattern for Longest Substring Without Repeating Characters (LeetCode #3): optimal O(n) time and O(n) auxiliary space.",
  },
  57: {
    levelNumber: 57,
    title: "Longest Palindromic Substring (LeetCode #5)",
    optimalCode: "s = input()\n\nif not s:\n    print(\"\")\nelse:\n    def expand(l, r):\n        while l >= 0 and r < len(s) and s[l] == s[r]:\n            l -= 1\n            r += 1\n        return s[l + 1:r]\n\n    longest = \"\"\n    for i in range(len(s)):\n        p1 = expand(i, i)\n        if len(p1) > len(longest):\n            longest = p1\n        p2 = expand(i, i + 1)\n        if len(p2) > len(longest):\n            longest = p2\n\n    print(longest)\n",
    timeComplexity: "O(n^2)",
    spaceComplexity: "O(1)",
    explanation: "Expanding around 2n - 1 centers checks palindromes in O(n^2) time with O(1) space, avoiding complex suffix trees.",
    keyTakeaway: "Core interview pattern for Longest Palindromic Substring (LeetCode #5): optimal O(n^2) time and O(1) auxiliary space.",
  },
  58: {
    levelNumber: 58,
    title: "Zigzag Conversion (LeetCode #6)",
    optimalCode: "s = input()\nnum_rows = int(input())\n\nif num_rows == 1 or num_rows >= len(s):\n    print(s)\nelse:\n    rows = [''] * num_rows\n    curr = 0\n    step = 1\n\n    for char in s:\n        rows[curr] += char\n        if curr == 0:\n            step = 1\n        elif curr == num_rows - 1:\n            step = -1\n        curr += step\n\n    print(''.join(rows))\n",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    explanation: "Simulating the row index direction bounce visits each character exactly once in O(n) time and O(n) space.",
    keyTakeaway: "Core interview pattern for Zigzag Conversion (LeetCode #6): optimal O(n) time and O(n) auxiliary space.",
  },
  59: {
    levelNumber: 59,
    title: "String to Integer (atoi) (LeetCode #8)",
    optimalCode: "import sys\nlines = sys.stdin.read().splitlines()\ns = lines[0] if lines else \"\"\n\ns = s.lstrip()\nif not s:\n    print(0)\nelse:\n    sign = 1\n    idx = 0\n    if s[0] == '-':\n        sign = -1\n        idx = 1\n    elif s[0] == '+':\n        idx = 1\n\n    val = 0\n    while idx < len(s) and s[idx].isdigit():\n        val = val * 10 + int(s[idx])\n        idx += 1\n\n    val = sign * val\n    INT_MIN = -2**31\n    INT_MAX = 2**31 - 1\n    if val < INT_MIN:\n        val = INT_MIN\n    elif val > INT_MAX:\n        val = INT_MAX\n\n    print(val)\n",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    explanation: "Finite-state machine parsing scans the string in linear O(n) time and strict O(1) space with proper 32-bit overflow guards.",
    keyTakeaway: "Core interview pattern for String to Integer (atoi) (LeetCode #8): optimal O(n) time and O(1) auxiliary space.",
  },
  60: {
    levelNumber: 60,
    title: "Longest Common Prefix (LeetCode #14)",
    optimalCode: "import sys\nline = sys.stdin.read().strip()\nstrs = line.split() if line else []\n\nif not strs:\n    print(\"\")\nelse:\n    strs.sort()\n    first, last = strs[0], strs[-1]\n    i = 0\n    while i < len(first) and i < len(last) and first[i] == last[i]:\n        i += 1\n    print(first[:i])\n",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    explanation: "Comparing only the lexicographically smallest and largest string determines the prefix in O(n * log m + m) time and O(1) space.",
    keyTakeaway: "Core interview pattern for Longest Common Prefix (LeetCode #14): optimal O(n) time and O(1) auxiliary space.",
  },
  61: {
    levelNumber: 61,
    title: "Reverse Integer (LeetCode #7)",
    optimalCode: "x = int(input())\n\nsign = -1 if x < 0 else 1\nrev = int(str(abs(x))[::-1]) * sign\n\nif rev < -2**31 or rev > 2**31 - 1:\n    print(0)\nelse:\n    print(rev)\n",
    timeComplexity: "O(log n)",
    spaceComplexity: "O(1)",
    explanation: "Digit extraction and 32-bit range verification runs in O(log_10 x) time and O(1) space.",
    keyTakeaway: "Core interview pattern for Reverse Integer (LeetCode #7): optimal O(log n) time and O(1) auxiliary space.",
  },
  62: {
    levelNumber: 62,
    title: "Palindrome Number (LeetCode #9)",
    optimalCode: "x = int(input())\n\nif x < 0 or (x % 10 == 0 and x != 0):\n    print(\"False\")\nelse:\n    rev = 0\n    while x > rev:\n        rev = rev * 10 + x % 10\n        x //= 10\n    if x == rev or x == rev // 10:\n        print(\"True\")\n    else:\n        print(\"False\")\n",
    timeComplexity: "O(log n)",
    spaceComplexity: "O(1)",
    explanation: "Reversing half of the number avoids integer overflow and executes in O(log_10 n) time and O(1) auxiliary space.",
    keyTakeaway: "Core interview pattern for Palindrome Number (LeetCode #9): optimal O(log n) time and O(1) auxiliary space.",
  },
  63: {
    levelNumber: 63,
    title: "Integer to Roman (LeetCode #12)",
    optimalCode: "num = int(input())\n\nmapping = [\n    (1000, \"M\"), (900, \"CM\"), (500, \"D\"), (400, \"CD\"),\n    (100, \"C\"), (90, \"XC\"), (50, \"L\"), (40, \"XL\"),\n    (10, \"X\"), (9, \"IX\"), (5, \"V\"), (4, \"IV\"), (1, \"I\")\n]\n\nres = []\nfor val, sym in mapping:\n    if num == 0:\n        break\n    count = num // val\n    if count > 0:\n        res.append(sym * count)\n        num -= val * count\n\nprint(\"\".join(res))\n",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    explanation: "Greedy subtraction with a static 13-symbol lookup table runs in O(1) time and O(1) space because num <= 3999.",
    keyTakeaway: "Core interview pattern for Integer to Roman (LeetCode #12): optimal O(n) time and O(1) auxiliary space.",
  },
  64: {
    levelNumber: 64,
    title: "Roman to Integer (LeetCode #13)",
    optimalCode: "s = input()\n\nvals = {'I': 1, 'V': 5, 'X': 10, 'L': 50, 'C': 100, 'D': 500, 'M': 1000}\ntotal = 0\nn = len(s)\n\nfor i in range(n):\n    if i + 1 < n and vals[s[i]] < vals[s[i + 1]]:\n        total -= vals[s[i]]\n    else:\n        total += vals[s[i]]\n\nprint(total)\n",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    explanation: "Lookahead comparison evaluates the subtractive rule in a single pass in O(n) time and O(1) space.",
    keyTakeaway: "Core interview pattern for Roman to Integer (LeetCode #13): optimal O(n) time and O(1) auxiliary space.",
  },
  65: {
    levelNumber: 65,
    title: "Median of Two Sorted Arrays (LeetCode #4)",
    optimalCode: "import sys\n\nlines = sys.stdin.read().splitlines()\nnums1 = list(map(int, lines[0].split())) if len(lines) > 0 and lines[0].strip() else []\nnums2 = list(map(int, lines[1].split())) if len(lines) > 1 and lines[1].strip() else []\n\nif len(nums1) > len(nums2):\n    nums1, nums2 = nums2, nums1\n\nm, n = len(nums1), len(nums2)\nimin, imax, half_len = 0, m, (m + n + 1) // 2\n\nwhile imin <= imax:\n    i = (imin + imax) // 2\n    j = half_len - i\n    if i < m and nums2[j - 1] > nums1[i]:\n        imin = i + 1\n    elif i > 0 and nums1[i - 1] > nums2[j]:\n        imax = i - 1\n    else:\n        if i == 0: max_of_left = nums2[j - 1]\n        elif j == 0: max_of_left = nums1[i - 1]\n        else: max_of_left = max(nums1[i - 1], nums2[j - 1])\n\n        if (m + n) % 2 == 1:\n            print(f\"{float(max_of_left):.1f}\")\n            break\n\n        if i == m: min_of_right = nums2[j]\n        elif j == n: min_of_right = nums1[i]\n        else: min_of_right = min(nums1[i], nums2[j])\n\n        median = (max_of_left + min_of_right) / 2.0\n        print(f\"{median:.1f}\")\n        break\n",
    timeComplexity: "O(log(min(m, n)))",
    spaceComplexity: "O(1)",
    explanation: "Binary searching partition cuts on the smaller array achieves optimal O(log(min(m, n))) time and O(1) space.",
    keyTakeaway: "Core interview pattern for Median of Two Sorted Arrays (LeetCode #4): optimal O(log(min(m, n))) time and O(1) auxiliary space.",
  },
  66: {
    levelNumber: 66,
    title: "Add Two Numbers (LeetCode #2)",
    optimalCode: "l1 = list(map(int, input().split()))\nl2 = list(map(int, input().split()))\n\ni, j = 0, 0\ncarry = 0\nres = []\n\nwhile i < len(l1) or j < len(l2) or carry:\n    val1 = l1[i] if i < len(l1) else 0\n    val2 = l2[j] if j < len(l2) else 0\n    total = val1 + val2 + carry\n    carry = total // 10\n    res.append(total % 10)\n    i += 1\n    j += 1\n\nprint(\" \".join(map(str, res)))\n",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    explanation: "Digit addition with carry runs in linear O(max(N, M)) time and O(max(N, M)) space.",
    keyTakeaway: "Core interview pattern for Add Two Numbers (LeetCode #2): optimal O(n) time and O(1) auxiliary space.",
  },
  67: {
    levelNumber: 67,
    title: "Remove Nth Node From End of List (LeetCode #19)",
    optimalCode: "nums = list(map(int, input().split()))\nn = int(input())\n\nidx_to_remove = len(nums) - n\ndel nums[idx_to_remove]\n\nif nums:\n    print(\" \".join(map(str, nums)))\nelse:\n    print(\"EMPTY\")\n",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    explanation: "Two-pointer gap tracking identifies and unlinks the nth node from end in a single O(L) pass and O(1) space.",
    keyTakeaway: "Core interview pattern for Remove Nth Node From End of List (LeetCode #19): optimal O(n) time and O(1) auxiliary space.",
  },
  68: {
    levelNumber: 68,
    title: "Valid Parentheses (LeetCode #20)",
    optimalCode: "s = input()\n\nmapping = {')': '(', '}': '{', ']': '['}\nstack = []\nvalid = True\n\nfor char in s:\n    if char in mapping:\n        top = stack.pop() if stack else '#'\n        if mapping[char] != top:\n            valid = False\n            break\n    else:\n        stack.append(char)\n\nif valid and not stack:\n    print(\"True\")\nelse:\n    print(\"False\")\n",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    explanation: "LIFO stack matching achieves optimal O(n) time and O(n) space.",
    keyTakeaway: "Core interview pattern for Valid Parentheses (LeetCode #20): optimal O(n) time and O(n) auxiliary space.",
  },
  69: {
    levelNumber: 69,
    title: "Letter Combinations of a Phone Number (LeetCode #17)",
    optimalCode: "import sys\nline = sys.stdin.read().strip()\n\nif not line:\n    print(\"NONE\")\nelse:\n    phone = {\n        '2': 'abc', '3': 'def', '4': 'ghi', '5': 'jkl',\n        '6': 'mno', '7': 'pqrs', '8': 'tuv', '9': 'wxyz'\n    }\n\n    res = ['']\n    for d in line:\n        if d in phone:\n            res = [prev + char for prev in res for char in phone[d]]\n\n    res.sort()\n    for item in res:\n        print(item)\n",
    timeComplexity: "O(4^n)",
    spaceComplexity: "O(1)",
    explanation: "Backtracking / product combination generates all 3^N * 4^M letter combinations in O(4^N) time.",
    keyTakeaway: "Core interview pattern for Letter Combinations of a Phone Number (LeetCode #17): optimal O(4^n) time and O(1) auxiliary space.",
  },
  70: {
    levelNumber: 70,
    title: "Regular Expression Matching (LeetCode #10)",
    optimalCode: "import sys\nlines = sys.stdin.read().splitlines()\ns = lines[0] if len(lines) > 0 else \"\"\np = lines[1] if len(lines) > 1 else \"\"\n\nm, n = len(s), len(p)\ndp = [[False] * (n + 1) for _ in range(m + 1)]\ndp[0][0] = True\n\nfor j in range(2, n + 1):\n    if p[j - 1] == '*':\n        dp[0][j] = dp[0][j - 2]\n\nfor i in range(1, m + 1):\n    for j in range(1, n + 1):\n        if p[j - 1] == '*':\n            dp[i][j] = dp[i][j - 2]\n            if p[j - 2] == '.' or p[j - 2] == s[i - 1]:\n                dp[i][j] = dp[i][j] or dp[i - 1][j]\n        elif p[j - 1] == '.' or p[j - 1] == s[i - 1]:\n            dp[i][j] = dp[i - 1][j - 1]\n\nprint(\"True\" if dp[m][n] else \"False\")\n",
    timeComplexity: "O(m * n)",
    spaceComplexity: "O(m * n)",
    explanation: "2D dynamic programming evaluates transitions in O(m * n) time and O(m * n) space.",
    keyTakeaway: "Core interview pattern for Regular Expression Matching (LeetCode #10): optimal O(m * n) time and O(m * n) auxiliary space.",
  },
};
